import { AuthContextProvider } from "@/contexts/authContext";
import Head from "next/head";
import Dashboard from "./dashboard";
import AuthenticationSwitcher from "@/components/authenticationSwitcher";
import DataContextProvider from "@/contexts/dataContext";

export default function Home() {
  return (
    <>
      <Head>
        <title>AGLA - Data Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthContextProvider>
        <DataContextProvider>
          <AuthenticationSwitcher />
        </DataContextProvider>
      </AuthContextProvider>
    </>
  );
}
